import { LearningSubmit } from '@/components/learning-submit';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireCurrentUser } from '@/lib/auth/session';
import { prisma } from '@/lib/prisma';
import { courseSources, ownedCourse, passageSnapshot } from '@/lib/courses/learning-service';
import { LearningError, learningButton, learningPanel } from '@/components/learning-ui';
import { analyzeLearningCourse } from '../learning-actions';
export const dynamic='force-dynamic';
export default async function CoursePage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string}>}) {
  const user=await requireCurrentUser();const {id}=await params;const search=await searchParams;
  const course=await ownedCourse(prisma,user.id,id).catch(()=>notFound());const snapshot=passageSnapshot(course);
  const assets=courseSources(course);
  const versions=await prisma.projectVersion.findMany({where:{userId:user.id,courseThemeId:id,mode:{in:['explain','summary','essential','visual']}},orderBy:{createdAt:'desc'},take:10,select:{id:true,mode:true,createdAt:true}});
  const sessions=await prisma.learningSession.findMany({where:{userId:user.id,courseThemeId:id},orderBy:{updatedAt:'desc'},take:10,select:{id:true,kind:true}});
  const pending=assets.flatMap(a=>a.extractions.filter(e=>e.quality==='needs-vision'&&!a.extractions.some(l=>l.unitKey===e.unitKey&&['ocr','reviewed'].includes(l.method))).map(e=>({id:e.id,label:`${a.imports[0]?.originalFileName} · ${e.unitKey}`})));
  const uncertain=assets.flatMap(a=>a.extractions.filter(e=>e.method==='ocr'&&!a.extractions.some(l=>l.unitKey===e.unitKey&&l.method==='reviewed')));
  return <main className="mx-auto grid max-w-3xl min-w-0 gap-6 break-words pb-10"><Link href="/courses" className="text-moss underline">← Mes cours</Link><header><h1 className="text-3xl font-bold">{course.title}</h1><p className="mt-4 text-xl">Que veux-tu faire ?</p></header><nav aria-label="Travailler ce cours" className="grid gap-4">{[['understand','Comprendre ce cours'],['revise','Réviser'],['homework','J’ai un devoir']].map(([path,label])=><Link key={path} className={`${learningButton} min-h-20 text-xl`} href={`/courses/${id}/${path}`}>{label}</Link>)}</nav><LearningError code={search.error}/><section className={learningPanel}><h2 className="text-lg font-bold">Lecture du cours</h2><p>{snapshot.passages.length?`${snapshot.passages.length} passages disponibles.`:'Ton cours est enregistré. Préparons sa lecture pour pouvoir travailler dessus.'}</p>{pending.length||uncertain.length?<p>Une partie du cours reste à lire ou à vérifier. Les exercices utilisent uniquement les passages vérifiés.</p>:null}<form action={analyzeLearningCourse}><input type="hidden" name="courseId" value={id}/><LearningSubmit className={learningButton}>Analyser ce cours</LearningSubmit></form><p className="text-sm text-ink/60">Lecture locale de tes documents enregistrés, sans nouvel envoi. Limites : 25 Mio et 40 pages ou images par document.</p></section>
  {pending.length?<section className={learningPanel}><h2 className="text-lg font-bold">Lire les pages en images</h2><p>Certaines pages sont des images. Elles doivent être analysées pour pouvoir expliquer le cours.</p><form action={analyzeLearningCourse} className="grid gap-3"><input type="hidden" name="courseId" value={id}/><fieldset className="grid gap-2"><legend>Choisis jusqu’à cinq pages</legend>{pending.map(p=><label key={p.id} className="flex items-start gap-3 py-2"><input type="checkbox" name="page" value={p.id} className="mt-1 size-5"/><span>{p.label}</span></label>)}</fieldset><label className="flex items-start gap-3"><input type="checkbox" name="consent" value="yes" required className="mt-1 size-5"/><span>J’autorise l’envoi des pages choisies au service d’analyse {process.env.OCR_PROVIDER==='openai'?'OpenAI':'configuré'}. Cette analyse peut être payante.</span></label><LearningSubmit className={learningButton}>Analyser les pages</LearningSubmit></form></section>:null}
  {uncertain.length?<section className={learningPanel}><h2 className="text-lg font-bold">Passages à vérifier</h2><p>Compare le texte reconnu à l’image avant de l’utiliser pour un exercice.</p>{uncertain.map(e=><Link className="text-moss underline" key={e.id} href={`/courses/${id}/reading/${e.id}`}>Vérifier {e.unitKey}</Link>)}</section>:null}
  {versions.length||sessions.length?<section className={learningPanel}><h2 className="text-lg font-bold">Reprendre mon travail</h2>{versions.map(v=><Link className="text-moss underline" key={v.id} href={`/courses/${id}/content/${v.id}`}>{({explain:'Explication',summary:'Résumé',essential:'Essentiel',visual:'Visuel'} as Record<string,string>)[v.mode]} · {v.createdAt.toLocaleDateString('fr-FR')}</Link>)}{sessions.map(s=><Link className="text-moss underline" key={s.id} href={`/courses/${id}/session/${s.id}`}>{s.kind==='revision'?'Reprendre une révision':'Reprendre un devoir'}</Link>)}</section>:null}
  <details className={learningPanel}><summary className="cursor-pointer font-bold">Documents et organisation</summary>{course.parts.map(part=><section key={part.id}><h2 className="font-semibold">{part.referenceLabel} {part.title}</h2>{part.placements.map(p=><p key={p.id}><a className="text-moss underline" href={`/api/sources/${p.sourceAssetId}/download`}>{p.sourceAsset.imports[0]?.originalFileName??'Original'}</a></p>)}</section>)}<Link href="/courses#organiser" className="text-moss underline">Organiser mes cours</Link></details></main>;
}
