import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireCurrentUser } from '@/lib/auth/session';
import { prisma } from '@/lib/prisma';
import { learningSchema, publicQuestion } from '@/lib/courses/learning-contract';
import { ownedSession } from '@/lib/courses/learning-service';
import { BackToCourse, LearningAudio, LearningBlocks, LearningError, SourceRefs, learningButton, learningPanel } from '@/components/learning-ui';
import { nextLearningStep, submitLearningAnswer } from '../../../learning-actions';

export default async function LearningSessionPage({params,searchParams}:{params:Promise<{id:string;sessionId:string}>;searchParams:Promise<{error?:string}>}) {
  const user=await requireCurrentUser();const {id,sessionId}=await params;
  const session=await ownedSession(prisma,user.id,sessionId).catch(()=>notFound());if(session.courseThemeId!==id)notFound();
  const output=learningSchema.parse(session.projectVersion.content);const position=session.position;
  const fields=<><input type="hidden" name="courseId" value={id}/><input type="hidden" name="sessionId" value={sessionId}/><input type="hidden" name="position" value={position}/></>;
  const last=session.attempts.filter(a=>a.questionIndex===position).at(-1);
  if(session.kind==='homework') {
    const h=output.homework;if(!h)notFound();
    const canSeeCorrection=session.attempts.length>0;
    return <div className="mx-auto grid max-w-2xl gap-6 break-words"><BackToCourse id={id}/><h1 className="text-3xl font-bold">Ton devoir, étape par étape</h1><LearningError code={(await searchParams).error}/><p role="status">{session.attempts.length?'Ta tentative est enregistrée':'Commençons par comprendre la consigne'}</p><section className={learningPanel}><h2 className="font-bold">La consigne</h2><p className="whitespace-pre-wrap">{session.instruction}</p><h2 className="font-bold">Avec des mots simples</h2><p>{h.rephrased}</p><SourceRefs courseId={id} refs={h.citations}/><h2 className="font-bold">Une petite question</h2><p>{h.check}</p></section><section className={learningPanel}><h2 className="font-bold">Premier indice</h2><LearningBlocks blocks={[h.hints[0]]} courseId={id}/>{position>0?<><h2 className="font-bold">Deuxième indice</h2><LearningBlocks blocks={[h.hints[1]]} courseId={id}/></>:null}</section><form action={submitLearningAnswer} className={learningPanel}>{fields}<label className="grid gap-2"><span className="font-bold">Écris ta réponse avec tes mots</span><textarea name="answer" required maxLength={3000} rows={6} defaultValue={session.attempts.at(-1)?.answer} className="min-w-0 rounded-xl border p-3"/></label><button className={learningButton}>Regarder ma réponse</button></form>{session.attempts.length?<section className={learningPanel}><h2 className="font-bold">Tu as commencé, continuons</h2><p>{session.attempts.at(-1)?.feedback}</p><p className="text-sm">Ce retour t’aide à relire ta réponse ; ce n’est pas une note.</p></section>:null}{position===0&&session.attempts.length>0?<form action={nextLearningStep}>{fields}<button className={learningButton}>J’ai besoin d’un deuxième indice</button></form>:null}{canSeeCorrection?<details className={learningPanel}><summary className="cursor-pointer font-bold">Comparer avec une correction expliquée</summary><LearningBlocks blocks={h.correction} courseId={id}/></details>:<p className="text-sm text-ink/70">Écris d’abord une tentative, même courte, pour pouvoir comparer avec la correction.</p>}<details className={learningPanel}><summary>Mes tentatives</summary>{session.attempts.map(a=><blockquote key={a.id} className="whitespace-pre-wrap border-l-2 pl-3">{a.answer}</blockquote>)}</details></div>;
  }
  const q=output.questions[position];
  if(!q)return <div className="mx-auto grid max-w-2xl gap-6"><BackToCourse id={id}/><h1 className="text-3xl font-bold">Révision terminée !</h1><p>Tu as travaillé {output.questions.length} questions.</p><p>{new Set(session.attempts.filter(a=>a.correct).map(a=>a.questionIndex)).size} questions réussies. Tu peux revenir au cours pour relire les passages utiles.</p><Link href={`/courses/${id}/revise`} className={learningButton}>Faire une autre révision</Link></div>;
  const visible=publicQuestion(q);
  // The component below is server-rendered; neither q nor output crosses a client boundary.
  const associationRights=q.type==='association'?q.expected.map(s=>s.split(' → ')[1]).sort():[];
  return <div className="mx-auto grid max-w-2xl min-w-0 gap-6 break-words"><BackToCourse id={id}/><h1 className="text-3xl font-bold">Réviser</h1><p role="status">Question {position+1} sur {output.questions.length} · {q.difficulty==='easy'?'Pour commencer':'Un peu plus loin'}</p><progress aria-label="Progression de la révision" value={position} max={output.questions.length} className="w-full"/><LearningError code={(await searchParams).error}/><section className={learningPanel}><h2 className="text-xl font-bold">{visible.prompt}</h2>{!last?<form action={submitLearningAnswer} className="grid min-w-0 gap-4">{fields}{['mcq','boolean'].includes(visible.type)?<fieldset className="grid gap-3"><legend className="sr-only">Ta réponse</legend>{visible.choices.map((choice,i)=><label key={i} className="flex items-start gap-3 rounded-xl border p-4"><input required type="radio" name="answer" value={choice} className="mt-1 size-5"/><span>{choice}</span></label>)}</fieldset>:visible.type==='order'?visible.choices.map((_,i)=><label key={i} className="grid gap-2"><span>Étape {i+1}</span><select required name="answer" className="min-w-0 rounded-xl border p-3"><option value="">Choisir</option>{visible.choices.map(c=><option key={c}>{c}</option>)}</select></label>):visible.type==='association'?visible.choices.map(c=><label key={c} className="grid gap-2"><span>{c}</span><select required name="answer" className="min-w-0 rounded-xl border p-3"><option value="">Associer à…</option>{associationRights.map(r=><option key={r} value={`${c} → ${r}`}>{r}</option>)}</select></label>):<label className="grid gap-2"><span>Le mot manquant</span><input required name="answer" maxLength={300} autoComplete="off" className="min-w-0 rounded-xl border p-3"/></label>}<button className={learningButton}>Vérifier ma réponse</button></form>:<div className="grid gap-4"><p role="status" className="font-bold">{last.correct?'Bien joué !':'Tu progresses : regardons ensemble.'}</p><p>Ta réponse : {last.answer}</p><p>Réponse attendue : {q.expected.join(' ; ')}</p><p>{last.feedback}</p><SourceRefs courseId={id} refs={q.citations}/><form action={nextLearningStep}>{fields}<button className={learningButton}>Question suivante</button></form></div>}</section><LearningAudio courseId={id} versionId={session.projectVersionId} audio={session.projectVersion.audio} audioKey={`question-${position}`} sessionId={sessionId}/>{last?<LearningAudio courseId={id} versionId={session.projectVersionId} audio={session.projectVersion.audio} audioKey={`feedback-${position}`} sessionId={sessionId}/>:null}</div>;
}
