import { LearningSubmit } from '@/components/learning-submit';
import Link from 'next/link';
import { ContinuousAudioPlayer } from './continuous-audio-player';
import { createLearningAudio } from '@/app/courses/learning-actions';
import { getStoredAudioPlayback, storedAudioExists } from '@/lib/audio-storage';
import type { LearningOutput } from '@/lib/courses/learning-contract';
import { rejectedProductionMessage } from '@/lib/courses/learning-errors';
export const learningButton='inline-flex min-h-12 items-center justify-center rounded-xl bg-moss px-5 py-3 text-center text-base font-semibold text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-moss disabled:opacity-50';
export const learningPanel='grid min-w-0 gap-4 rounded-2xl border border-ink/10 bg-white p-4 sm:p-6';
export function LearningPreparationError({code,courseId,activity}:{code?:string;courseId:string;activity?:string}) {
  if(!code)return null;
  if(code==='generation')return <p role="alert" className="rounded-xl bg-amber-50 p-4 text-amber-950">{rejectedProductionMessage(activity)}</p>;
  if(code==='reading')return <div role="alert" className={learningPanel}><p>Je n’arrive pas encore à lire assez de texte pour cette activité. Tu peux améliorer la lecture des pages en images ou ajouter un document plus lisible.</p><Link className="text-moss underline" href={`/courses/${courseId}#course-reading`}>Améliorer la lecture du cours</Link></div>;
  return <LearningError code={code}/>;
}
export function LearningError({code}:{code?:string}) {if(!code)return null;return <p role="alert" className="rounded-xl bg-amber-50 p-4 text-amber-950">{code==='source'?'Je ne peux pas le vérifier avec ce cours. Vérifie sa lecture : une partie peut être incertaine, trop longue ou insuffisante pour cette activité.':code==='provider'?'Ce service n’est pas encore configuré. Tu peux toujours lire les passages disponibles.':code==='timeout'?'La préparation a dépassé le délai autorisé. Aucun contenu incomplet n’a remplacé ton travail. Tu peux réessayer plus tard.':code==='pending'?'Cette préparation est déjà en cours ou terminée. Recharge la page. Si elle reste bloquée, demande de l’aide au propriétaire du site.':'La préparation n’a pas abouti. Aucun contenu incomplet n’a remplacé ton travail. Tu peux réessayer.'}</p>;}
export function BackToCourse({id}:{id:string}) {return <Link className="w-fit rounded py-2 text-moss underline focus-visible:outline" href={`/courses/${id}`}>← Retour au cours</Link>;}
export function SourceRefs({courseId,refs}:{courseId:string;refs:Array<{passageId:string;quote:string}>}) {return <details className="rounded-lg border border-ink/10 p-3 text-sm"><summary className="cursor-pointer font-semibold">Voir dans mon cours</summary><ul className="mt-3 grid gap-3">{refs.map((r,i)=><li key={`${r.passageId}-${i}`}><blockquote className="whitespace-pre-wrap border-l-2 border-moss pl-3">{r.quote}</blockquote><Link className="text-moss underline" href={`/courses/${courseId}/passage/${r.passageId}`}>Ouvrir le passage source</Link></li>)}</ul></details>;}
export function LearningBlocks({blocks,courseId}:{blocks:LearningOutput['blocks'];courseId:string}) {return <div className="grid gap-4">{blocks.map((b,i)=><section className={learningPanel} key={i}><h2 className="text-lg font-bold text-moss">{b.title??(b.kind==='example'?'Exemple pour comprendre':'Explication du cours')}</h2><p className="whitespace-pre-wrap leading-7">{b.text}</p><SourceRefs courseId={courseId} refs={b.citations}/></section>)}</div>;}
export function CourseVisual({visual,courseId}:{visual:NonNullable<LearningOutput['visual']>;courseId:string}) {
  return <section className={learningPanel}><h2 className="text-xl font-bold">{visual.title}</h2><ol className={visual.type==='comparison'?'grid gap-4 sm:grid-cols-2':'grid gap-4 border-l-4 border-moss pl-4'}>{visual.items.map((item,i)=><li key={i} className="min-w-0 rounded-xl bg-paper p-4"><h3 className="font-bold">{['timeline','steps'].includes(visual.type)?`${i+1}. `:''}{item.label}</h3>{item.parent>=0?<p className="text-sm text-ink/70">En lien avec : {visual.items[item.parent].label}</p>:null}<p className="mt-2 leading-6">{item.detail}</p><SourceRefs courseId={courseId} refs={item.citations}/></li>)}</ol></section>;
}
export async function LearningAudio({courseId,versionId,audio,audioKey,sessionId}:{courseId:string;versionId:string;audio:unknown;audioKey:string;sessionId?:string}) {
  const record=(audio as Record<string,{file:string}>)[audioKey];
  const playback=record&&await storedAudioExists(record.file)?await getStoredAudioPlayback(record.file):null;
  const base=`/api/courses/${courseId}/audio/${versionId}?key=${encodeURIComponent(audioKey)}${sessionId?`&session=${encodeURIComponent(sessionId)}`:''}`;
  return <section className={learningPanel}><h2 className="text-lg font-bold">Écouter</h2><p className="text-sm text-ink/65">Une voix de synthèse lit exactement ce texte.</p>{playback?<ContinuousAudioPlayer simple sources={playback.segments.map((_,i)=>`${base}&segment=${i}`)}/>:<form action={createLearningAudio}><input type="hidden" name="courseId" value={courseId}/><input type="hidden" name="versionId" value={versionId}/><input type="hidden" name="sessionId" value={sessionId??''}/><input type="hidden" name="audioKey" value={audioKey}/><LearningSubmit className={learningButton}>Préparer l’écoute</LearningSubmit><p className="mt-2 text-sm text-ink/60">Utilise le service vocal configuré ; cette préparation peut être payante. Les écoutes suivantes réutilisent l’audio.</p></form>}</section>;
}
